#!/bin/bash

if [ -z "$1" ] && [ -z "$2" ]; then
    echo "./docker-import [path to sql file] [database]"

elif [ "$1" ] && [ -z "$2" ]; then
    mysql -u root -p1234 -h 0.0.0.0 --port=3307 < "$1"

elif [ "$1" ] && [ "$2" ]; then 
    mysql -u root -p1234 $2 -h 0.0.0.0 --port=3307 < "$1"
fi